### ISSUE TITLE
option for checks

### ISSUE THREAD

**Issue by bhcleek** [dominikh/staticcheck-action#1]
Thank you for creating this action; it will be incredibly useful for us.

I work with a large monorepo in which `staticcheck` is used in a few different scenarios, and this action will work wonderfully in most of them, but there's one scenario that wouldn't be covered by this action.

We need to be able to pass the checks on the commandline so that any checks managed in nested staticcheck.conf files can be overridden easily, because we have a set of checks that are always expected; the nested staticcheck files are effectively extensions for teams that want to add additional checks for their code domain.

Would you be willing to add an option, `checks` that defines checks that will be passed on the commandline so that it takes precedence over checks defined in config files? I would be willing to contribute this change if you'd be willing to accept it, but don't want to implement it for some reason.

**Comment by dominikh** [comment]
Sure, I can add that. No need to send a PR.

**Comment by bhcleek** [comment]
Thank you 🙇

**Comment by dominikh** [comment]
Let me know if this works and I'll make a new release.

**Comment by bhcleek** [comment]
This looks great. I'll try to test it this weekend, but it may be early next week before I can affirmatively verify.
