### ISSUE TITLE
/home/runner/go/bin/staticcheck: No such file or directory

### ISSUE THREAD

**Issue by gebn** [dominikh/staticcheck-action#14]
Hi folks, given this Actions step:

```yaml
    - name: Run Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: 2023.1.5
        install-go: false
```

My [job](https://github.com/gebn/tflcycles_exporter/actions/runs/5957462012/job/16160160346) produces:

```
Run dominikh/staticcheck-action@v1.3.0
Run actions/cache@v3
Cache not found for input keys: staticcheck-Linux--3166c0793d31ad4de97784f1bba57d497ec[58](https://github.com/gebn/tflcycles_exporter/actions/runs/5957462012/job/16160160346#step:4:61)1bc, staticcheck-Linux--
Run export STATICCHECK_CACHE="/home/runner/work/_temp/staticcheck"
go: downloading honnef.co/go/tools v0.4.5
go: downloading golang.org/x/tools v0.9.4-0.20230[60](https://github.com/gebn/tflcycles_exporter/actions/runs/5957462012/job/16160160346#step:4:63)1214343-86c93e8732cc
go: downloading golang.org/x/exp/typeparams v0.0.0-20221208152030-732eee02a75a
go: downloading golang.org/x/sys v0.8.0
go: downloading github.com/BurntSushi/toml v1.2.1
go: downloading golang.org/x/mod v0.10.0
/home/runner/work/_temp/54b11b8f-c246-4f6a-b5d2-9b7211[62](https://github.com/gebn/tflcycles_exporter/actions/runs/5957462012/job/16160160346#step:4:65)39b0.sh: line 12: /home/runner/go/bin/staticcheck: No such file or directory
Error: Process completed with exit code 127.
```

I've tried manually `go install`ing `staticcheck@2023.1.5`, which works normally. 

The full CI config can be found [here](https://github.com/gebn/tflcycles_exporter/blob/staticcheck-action/.github/workflows/ci.yaml#L36-L40).

What am I doing wrong? Happy to contribute a docs improvement to stop others falling into the same trap.

**Comment by dominikh** [comment]
My hypothesis is that it's caused by you setting GOOS and GOARCH. That'll affect the building of the `staticcheck` binary; the CI runner is Linux on x86, and it won't be able to run binaries built for ARM, or Windows.

**Comment by gebn** [comment]
Thanks @dominikh! Adding `if: env.GOOS == 'linux' && env.GOARCH == 'amd64'` to the step has fixed it. I'm surprised the error was "file not found" rather than something like "cannot execute binary file: Exec format error".
