### ISSUE TITLE
Add a `v1` tag following actions version recommendation

### ISSUE THREAD

**Issue by prince-chrismc** [dominikh/staticcheck-action#2]
It would be great to follow the recommendation of having a major tag. https://github.com/actions/toolkit/blob/master/docs/action-versioning.md

Having a "major" tag means way less changes to workflows, everyone gets to enjoy all the bug fixes and new features. It's easy to opt out and use a full tag which should move =)

**Comment by dominikh** [comment]
I expected GitHub to do this automatically, based on Semver, but I guess not.

**Comment by prince-chrismc** [comment]
Sadly no, it's an extra step for maintainers 🤷

**Comment by dominikh** [comment]
I've pushed a `v1` tag. Here's hoping I'll remember to update it in the future.
