### ISSUE TITLE
Force success status code even if staticcheck reports errors

### ISSUE THREAD

**Issue by ayoubfaouzi** [dominikh/staticcheck-action#7]
Hello @dominikh 

go-lint had an option where you can set-exit-code so even if there are failures, you can still make the command succeed.

I was not able to find a similar flag for staticcheck so I can pass it via the `options`, do you think it makes sense do add one in the action level ?

Cheers.

**Comment by dominikh** [comment]
Staticcheck has the `-fail` flag:

```
  -fail checks
    	Comma-separated list of checks that can cause a non-zero exit status. (default "all")
```

Setting it to some value like "none" would make it never return non-zero. But I don't think this option is currently settable via staticcheck-action.

What would be the use of this in the context of CI?

**Comment by ayoubfaouzi** [comment]
I think what you suggested solves my issue, thanks a lot @dominikh
